export const porducts = [
    {
        id: 1,
        title: "Heavenly",
        price: 21,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p1.png",
        quantity:1,
    },
    {
        id: 2,
        title: "Little italy",
        price: 15,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p2.png",
        quantity: 1,
    },
    {
        id: 3,
        title: "chicago",
        price: 10,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p3.png",
        quantity: 1,
    },
    {
        id: 4,
        title: "prime",
        price: 21,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p1.png",
        quantity: 1,
    },
    {
        id: 5,
        title: "St. Louis",
        price: 21,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p4.png",
        quantity: 1,
    },
    {
        id: 6,
        title: "Sicilian",
        price: 21,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p1.png",
        quantity: 1,
    },
    {
        id: 7,
        title: "Campagnola",
        price: 10,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p3.png",
        quantity: 1,
    },
    {
        id: 8,
        title: "Heavenly",
        price: 21,
        desc: " essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,.",
        img: "/imgs/p1.png",
        quantity: 1,
    },

]